package com.lirxowo.smallplane.earlydisplay;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Pixel art generated by {@code tools/generate_plane_sprite.py}.
 * <p>
 * Runs of horizontally adjacent pixels sharing a color are merged once at load time, so drawing a
 * sprite is a flat loop over a few quads instead of one quad per pixel.
 */
final class PixelSprite {
    private static final Logger LOGGER = LoggerFactory.getLogger(PixelSprite.class);

    private static final String TOKEN_SIZE = "size";
    private static final String TOKEN_COLOR = "color";
    private static final String TOKEN_ROW = "row";
    private static final String COMMENT_PREFIX = "#";
    /** Every run is stored as the four consecutive values x, y, length, color. */
    private static final int RUN_STRIDE = 4;

    private final int width;
    private final int height;
    private final int[] runs;

    private PixelSprite(int width, int height, int[] runs) {
        this.width = width;
        this.height = height;
        this.runs = runs;
    }

    int width() {
        return width;
    }

    int height() {
        return height;
    }

    void draw(QuadBatch batch, float left, float top, float scale) {
        for (int i = 0; i < runs.length; i += RUN_STRIDE) {
            float x0 = left + runs[i] * scale;
            float y0 = top + runs[i + 1] * scale;
            batch.colored(x0, y0, x0 + runs[i + 2] * scale, y0 + scale, runs[i + 3]);
        }
    }

    static @Nullable PixelSprite load(String resource) {
        try (InputStream stream = PixelSprite.class.getResourceAsStream(resource)) {
            if (stream == null) {
                LOGGER.warn("Sprite {} is missing from the mod jar", resource);
                return null;
            }
            return parse(new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8)));
        } catch (IOException | RuntimeException e) {
            LOGGER.warn("Failed to read sprite {}", resource, e);
            return null;
        }
    }

    private static PixelSprite parse(BufferedReader reader) throws IOException {
        Map<Character, Integer> palette = new HashMap<>();
        List<String> rows = new ArrayList<>();
        int declaredWidth = 0;
        int declaredHeight = 0;

        for (String line = reader.readLine(); line != null; line = reader.readLine()) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith(COMMENT_PREFIX)) {
                continue;
            }
            String[] tokens = trimmed.split("\\s+");
            switch (tokens[0]) {
                case TOKEN_SIZE -> {
                    declaredWidth = Integer.parseInt(tokens[1]);
                    declaredHeight = Integer.parseInt(tokens[2]);
                }
                case TOKEN_COLOR -> palette.put(tokens[1].charAt(0), (int) Long.parseLong(tokens[2], 16));
                case TOKEN_ROW -> rows.add(tokens[1]);
                default -> throw new IllegalArgumentException("Unknown sprite directive " + tokens[0]);
            }
        }

        if (rows.size() != declaredHeight) {
            throw new IllegalArgumentException("Sprite declares " + declaredHeight + " rows but has " + rows.size());
        }
        return new PixelSprite(declaredWidth, declaredHeight, buildRuns(rows, declaredWidth, palette));
    }

    private static int[] buildRuns(List<String> rows, int width, Map<Character, Integer> palette) {
        List<int[]> runs = new ArrayList<>();
        for (int y = 0; y < rows.size(); y++) {
            String row = rows.get(y);
            if (row.length() != width) {
                throw new IllegalArgumentException("Sprite row " + y + " is not " + width + " pixels wide");
            }
            int runStart = -1;
            int runColor = 0;
            for (int x = 0; x <= width; x++) {
                int color = x < width ? palette.getOrDefault(row.charAt(x), 0) : 0;
                if (color == runColor) {
                    continue;
                }
                if (runStart >= 0) {
                    runs.add(new int[] { runStart, y, x - runStart, runColor });
                }
                runStart = color == 0 ? -1 : x;
                runColor = color;
            }
        }

        int[] packed = new int[runs.size() * RUN_STRIDE];
        for (int i = 0; i < runs.size(); i++) {
            System.arraycopy(runs.get(i), 0, packed, i * RUN_STRIDE, RUN_STRIDE);
        }
        return packed;
    }
}
