org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=smallplane
mod_name=Small Plane
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.lirxowo.smallplane

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.aliyun.com|*.tencentyun.com|mirrors.cloud.tencent.com
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.aliyun.com|*.tencentyun.com|mirrors.cloud.tencent.com
