#!/usr/bin/env python3
"""Generates the pixel art used by the early loading screen mini game.

The sprite is defined as a left half plus a centre column and mirrored, so the
plane is symmetric by construction.

Outputs:
  src/main/resources/smallplane/sprites/plane.spr  - consumed by PixelSprite
  tools/preview/plane.png                          - human readable preview
"""

import os
import struct
import zlib

PALETTE = {
    "O": 0xFF151A2B,  # outline
    "B": 0xFFB9C2D0,  # fuselage
    "W": 0xFFEDF1F7,  # wings
    "C": 0xFF4FC3F7,  # cockpit
    "Y": 0xFFFFC94A,  # wing marking
    "F": 0xFFFF7A1A,  # exhaust flame
}

TRANSPARENT = "."

# Left half of the plane, column 6 is the centre line. Top-down view, nose up.
HALF_ROWS = [
    "......C",
    ".....OC",
    ".....OB",
    "....OOB",
    "..OOWWB",
    ".OWWWWB",
    "OWWYWWB",
    ".OOOWWB",
    ".....OB",
    "...OOOB",
    ".....FF",
]

PREVIEW_SCALE = 8
SPRITE_PATH = os.path.join("src", "main", "resources", "smallplane", "sprites", "plane.spr")
PREVIEW_PATH = os.path.join("tools", "preview", "plane.png")


def mirror(half):
    return half + half[:-1][::-1]


def build_rows():
    rows = [mirror(half) for half in HALF_ROWS]
    width = len(rows[0])
    for index, row in enumerate(rows):
        if len(row) != width:
            raise ValueError("row %d has width %d, expected %d" % (index, len(row), width))
        unknown = set(row) - set(PALETTE) - {TRANSPARENT}
        if unknown:
            raise ValueError("row %d uses undefined colors %s" % (index, sorted(unknown)))
    return rows


def write_sprite(rows):
    width, height = len(rows[0]), len(rows)
    lines = [
        "# Generated by tools/generate_plane_sprite.py - do not edit by hand.",
        "size %d %d" % (width, height),
    ]
    lines += ["color %s %08X" % (char, argb) for char, argb in PALETTE.items()]
    lines += ["row %s" % row for row in rows]

    os.makedirs(os.path.dirname(SPRITE_PATH), exist_ok=True)
    with open(SPRITE_PATH, "w", encoding="ascii", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    return width, height


def png_chunk(tag, payload):
    return (struct.pack(">I", len(payload)) + tag + payload
            + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF))


def write_preview(rows):
    width, height = len(rows[0]) * PREVIEW_SCALE, len(rows) * PREVIEW_SCALE
    raw = bytearray()
    for row in rows:
        scanline = bytearray()
        for char in row:
            argb = PALETTE.get(char, 0)
            pixel = bytes(((argb >> 16) & 0xFF, (argb >> 8) & 0xFF, argb & 0xFF, (argb >> 24) & 0xFF))
            scanline += pixel * PREVIEW_SCALE
        for _ in range(PREVIEW_SCALE):
            raw += b"\x00" + scanline

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    data = (b"\x89PNG\r\n\x1a\n"
            + png_chunk(b"IHDR", header)
            + png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
            + png_chunk(b"IEND", b""))

    os.makedirs(os.path.dirname(PREVIEW_PATH), exist_ok=True)
    with open(PREVIEW_PATH, "wb") as handle:
        handle.write(data)


def main():
    rows = build_rows()
    width, height = write_sprite(rows)
    write_preview(rows)
    print("%s (%dx%d)" % (SPRITE_PATH, width, height))
    print(PREVIEW_PATH)
    for row in rows:
        print("  " + row.replace(TRANSPARENT, " "))


if __name__ == "__main__":
    main()
